/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parcial_3_diaz_vivas.ASOCIACION;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    ASOCIACION aso;
   
           
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        aso = new ASOCIACION();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIR = new javax.swing.JButton();
        CARGAR_DATOS = new javax.swing.JButton();
        BUSCAR_HABITANTES_APTO = new javax.swing.JButton();
        BUSCAR_VECINO = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setBackground(new java.awt.Color(255, 153, 153));
        SALIR.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        SALIR.setText("X");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 70, 40));

        CARGAR_DATOS.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        CARGAR_DATOS.setText("CARGAR DATOS");
        CARGAR_DATOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGAR_DATOSActionPerformed(evt);
            }
        });
        getContentPane().add(CARGAR_DATOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 300, 60));

        BUSCAR_HABITANTES_APTO.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        BUSCAR_HABITANTES_APTO.setText("BUSCAR HABITANTES APTO");
        BUSCAR_HABITANTES_APTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_HABITANTES_APTOActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR_HABITANTES_APTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 300, 60));

        BUSCAR_VECINO.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        BUSCAR_VECINO.setText("BUSCAR VECINO");
        BUSCAR_VECINO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCAR_VECINOActionPerformed(evt);
            }
        });
        getContentPane().add(BUSCAR_VECINO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 300, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AtardecerBello.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void CARGAR_DATOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGAR_DATOSActionPerformed

        try {
            aso.leer_datos("test"+ File.separator+ "datosparcial.csv");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CARGAR_DATOSActionPerformed

    private void BUSCAR_VECINOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR_VECINOActionPerformed
           aso.introducirCI();
            
    }//GEN-LAST:event_BUSCAR_VECINOActionPerformed

    private void BUSCAR_HABITANTES_APTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCAR_HABITANTES_APTOActionPerformed
        // TODO add your handling code here:
        
        String edificio = JOptionPane.showInputDialog(null, "Ingrese el nombre del edificio donde vive el inquilino: ");
        String apto = JOptionPane.showInputDialog(null, "Ingrese el numero de apartamento donde vive el inquilino: ");
        aso.buscarHabitantes(edificio, apto);
        
        
        
//        int prueba1;
//        int prueba2;
//        int prueba3;
//        int prueba4;
//       prueba1 = prueba.hashHabitantes("Los Cedros", "31", 169);
//     prueba4= prueba.hashHabitantes("Los Cedros", "32", 169);
//       prueba2 = prueba.hashHabitantes("Los Cedros", "33", 169);
////      prueba2= prueba.hashHabitantes("Los Cedros", "32", 169);
//     prueba3= prueba.hashHabitantes("Los Cedros", "34", 169);
//        System.out.println(prueba1);
//      System.out.println(prueba2);
//      System.out.println(prueba3);
//      System.out.println(prueba4);
    }//GEN-LAST:event_BUSCAR_HABITANTES_APTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR_HABITANTES_APTO;
    private javax.swing.JButton BUSCAR_VECINO;
    private javax.swing.JButton CARGAR_DATOS;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
